api:
  key: wQJHAySx4hd8ZemgBafh21H2yQv4TOk8l3f3qxlgmyAu5aqbjUiUjMGf47EyWve3
  secret: Anoek8oF21CG375gcYrANn6ahiQ4nXPVgmCwPsNjqi7UzFldVAr39xGXaPSJlvXK
  paper: true
shadow:
  enabled: true
  market: prod
  maker_queue_alpha: 0.85
balance_check:
  enabled: true
risk:
  stop_to_usdt: false
  exit_after_stop: false
ui:
  enabled: true
  refresh_hz: 8
  alt_screen: true
  min_refresh_ms: 150
strategy:
  symbol: LINKUSDT
  paper_cash: 1000
  quote_size: 100.0
  target_pct: 0.26
  min_spread_pct: 0.05
econ:
  min_net_pct: 0.01
  enforce_post_only: true
  maker_fee_pct: 0.1
  taker_fee_pct: 0.1
  post_only: true
  depth_level: 5
  reorder_interval: 1.0
  cancel_timeout: 10
  status_poll_interval: 2.0
  stats_interval: 30.0
  ws_timeout: 2.0
  bootstrap_on_idle: true
  rest_bootstrap_interval: 3.0
  plan_log_interval: 5.0
  journal_interval: 10.0
  aggressive: false
  aggressive_bps: 0.0
scanner:
  enabled: true
  quote: USDT
  min_price: 0.01
  min_vol_usdt_24h: 3000000
  top_by_volume: 120
  max_pairs: 60
  min_spread_bps: 5.0
  vol_bars: 30
  score:
    w_spread: 1.0
    w_vol: 0.3
  whitelist: []
  blacklist:
  - BUSDUSDT
  - USDCUSDT
  - FDUSDUSDT
  - TUSDUSDT
